name: Generate Snake

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: deVich27
          outputs: dist/github-contribution-grid-snake.svg?color_snake=%23000000&color_dots=%23eeeeee,%23cccccc,%23999999,%23555555,%23000000

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update snake" || exit 0
          git push
